### ISSUE TITLE
Mautic.com availability?

### ISSUE THREAD

**Issue by cathalgarvey** [mautic/mautic-chat#1]
This addon looks like it would be valuable for multi-user accounts (which is pro right now, hopefully a modest number in a free account will be permitted someday), but isn't available to activate on mautic.com. Will it be?

**Comment by dbhurley** [comment]
This may be something that's re-integrated. Due to the success of third party chat clients and the proliferation of options recently it was withdrawn from the platform. However, there has been some discussion about completing the bundle and making it available for use. And with Mautic there are no free vs paid accounts - every account can use Mautic with _unlimited_ users. 

Keep in mind that Mautic.com is a hosted service provided by a third-party company, Allyde, which runs Mautic but also has additional custom add-ons they have written to include other features.

**Comment by RCheesley** [comment]
@dbhurley let's close this issue down and maybe even the repo itself, if it's not being supported any more?
